config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root 'static_pages#home'

  get '/signup',      to: 'users#new'
  get '/signin',      to: 'sessions#new'
  get '/help',        to: 'static_pages#help'
  get '/about',       to: 'static_pages#about'
  get '/contact',     to: 'static_pages#contact'

  delete '/signout',     to: 'sessions#destroy'
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    = link_to "Rails Tutorial", "http://railstutorial.org"
    by Micheal Hartl
  %nav
    %ul
      %li= link_to "About",       about_path
      %li= link_to "Contact",     contact_path
      %li= link_to "News",        "http://news.railstutorial.org/"

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "sample app", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Home",      root_path
          %li= link_to "Help",      help_path
          - if signed_in?
            %li= link_to "Users", users_path
            %li.dropdown#fat-menu
              %a.dropdown-toggle{href: '#', data: { toggle: "dropdown"}}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li= link_to "Sign out", signout_path, method: "delete"
          - else
            %li= link_to "Sign in", signin_path

app/views/layouts/_shim.html.haml
/[if It IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        .alert{class: "alert-#{key}"}= value
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?